name: jupyterlab-extension-examples
channels:
  - conda-forge
  - conda-forge/label/jupyterlab_beta
dependencies:
  - jupyterlab>=4.0.0b0
  - nodejs=18
  - pytest
  - pytest-check-links
  - python=3
  - yarn
